# Generated by Django 3.0.5 on 2020-04-25 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_way', '0003_synergyuser_synergy_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AlterField(
            model_name='synergyuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.date(2020, 4, 26), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='synergyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
